POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "password": "password",
  "email": "asd",
  "username": "sara",
  "name": "pekka",
  "role": "admin"
}

### Post missing fields
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "pekka",
  "role": "admin"
}
